/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.hotel.ms.gui;

import az.hotel.ms.dao.BookingDao;
import az.hotel.ms.dao.ClientDao;
import az.hotel.ms.dao.RoomDao;
import az.hotel.ms.model.Booking;
import az.hotel.ms.model.Client;
import az.hotel.ms.model.Room;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class EditBookingFrame extends javax.swing.JFrame {

    private BookingDao bookingDao;
    private ClientDao clientDao;
    private RoomDao roomDao;
    private Long selectedId;
    private MainFrame aThis;
    public EditBookingFrame() {
        initComponents();
    }

    EditBookingFrame(BookingDao bookingDao, ClientDao clientDao, RoomDao roomDao, Long selectedId, MainFrame aThis) {
           try {
            initComponents();
            this.bookingDao = bookingDao;
            this.clientDao = clientDao;
            this.roomDao = roomDao;
            this.selectedId = selectedId;
            this.aThis = aThis;
            Booking booking = bookingDao.getBookingById(selectedId);
            editClientCombo(booking.getClient());
            editRoomCombo(booking.getRoom());
            checkInTxt.setDate(booking.getCheckIn());
            checkOutTxt.setDate(booking.getCheckOut());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkInTxt = new com.toedter.calendar.JDateChooser();
        checkOutTxt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        roomNumberCmb = new javax.swing.JComboBox<>();
        clientCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Room Number");

        jLabel2.setText("Client Fullname");

        jLabel3.setText("Check In");

        jLabel4.setText("Check Out");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        roomNumberCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Number" }));
        roomNumberCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberCmbActionPerformed(evt);
            }
        });

        clientCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Client" }));
        clientCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roomNumberCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkInTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(checkOutTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNumberCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(checkInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkOutTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void editRoomCombo(Room r) {
        
        try {
            DefaultComboBoxModel roomCombo = (DefaultComboBoxModel) roomNumberCmb.getModel();
            
            List<Room> roomList = roomDao.getRoomList();
            for(Room room: roomList){
                
                roomCombo.addElement(room);
            }
            roomCombo.setSelectedItem(r);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void editClientCombo(Client c) {
        
        try {
            DefaultComboBoxModel clientCombo = (DefaultComboBoxModel) clientCmb.getModel();
            
            List<Client> clientList = clientDao.getClientList();
            for(Client client: clientList){
                
                clientCombo.addElement(client);
            }
            clientCombo.setSelectedItem(c);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try{
            Client client = (Client) clientCmb.getSelectedItem();
            Room room = (Room) roomNumberCmb.getSelectedItem();
            Date checkIn =  checkInTxt.getDate();
            Date checkOut = checkOutTxt.getDate();
            System.out.println("sleedted"+selectedId);
            Booking booking = bookingDao.getBookingById(selectedId);
            booking.setClient(client);
            booking.setRoom(room);
            booking.setCheckIn(checkIn);
            booking.setCheckOut(checkOut);
            bookingDao.updateBooking(booking);
            JOptionPane.showMessageDialog(null,"Booking has been successfully updated!");
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Problem! Booking has not been successfully updated!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        try {
            aThis.showBookingData(bookingDao.getBookingList());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void roomNumberCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberCmbActionPerformed

    private void clientCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientCmbActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
           clientCmb.setSelectedIndex(0);
           roomNumberCmb.setSelectedIndex(0);
           checkInTxt.setDateFormatString("");
           checkOutTxt.setDateFormatString("");
           
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser checkInTxt;
    private com.toedter.calendar.JDateChooser checkOutTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> clientCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> roomNumberCmb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
