/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.hotel.ms.gui;

import az.hotel.ms.dao.BookingDao;
import az.hotel.ms.dao.ClientDao;
import az.hotel.ms.dao.PaymentDao;
import az.hotel.ms.dao.PaymentOptDao;
import az.hotel.ms.dao.RoomDao;
import az.hotel.ms.model.Booking;
import az.hotel.ms.model.Client;
import az.hotel.ms.model.Payment;
import az.hotel.ms.model.PaymentOpt;
import az.hotel.ms.model.Room;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class EditPaymentFrame extends javax.swing.JFrame {

   private  PaymentDao paymentDao;
   private BookingDao bookingDao;
   private ClientDao clientDao;
   private RoomDao roomDao;
   private PaymentOptDao paymentOptDao;
   private Long selectedId;
   private MainFrame aThis;
    public EditPaymentFrame() {
        initComponents();
    }


    EditPaymentFrame(PaymentDao paymentDao, PaymentOptDao paymentOptDao, Long selectedId, MainFrame aThis) {
        try {
           initComponents();
           this.paymentDao = paymentDao;
           this.paymentOptDao = paymentOptDao;
           this.selectedId = selectedId;
           Payment payment = paymentDao.getPaymentById(selectedId);
           cardNumberTxt.setText(String.valueOf(payment.getCardNumber()));
           amountTxt.setText(String.valueOf(payment.getTotalAmount()));
           editOptionCombo(payment.getPaymentOpt());
           
       } catch (Exception ex) {
           ex.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cardNumberTxt = new javax.swing.JTextField();
        amountTxt = new javax.swing.JTextField();
        paymentOptionCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Card Number");

        jLabel4.setText("Total Amount");

        jLabel5.setText("Payment Option");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        paymentOptionCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Option" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(148, 148, 148)
                        .addComponent(paymentOptionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardNumberTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cardNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paymentOptionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
       try {
           
           Long cardNumber = Long.parseLong(cardNumberTxt.getText());
           Double amount = Double.parseDouble(amountTxt.getText());
           PaymentOpt paymentOpt = (PaymentOpt) paymentOptionCmb.getSelectedItem(); 
           Payment payment = paymentDao.getPaymentById(selectedId);
           payment.setCardNumber(cardNumber);
           payment.setTotalAmount(amount);
           payment.setPaymentOpt(paymentOpt);
           paymentDao.updatePayment(payment);
           JOptionPane.showMessageDialog(null, "Payment hass been succesfully updated!");
           
       } catch (Exception ex) {
           ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Problem! Payment has not been successfully updated!","Error",JOptionPane.ERROR);
       }
       this.dispose();
       try {
           aThis.showPaymentData(paymentDao.getPaymentList());
       } catch (Exception ex) {
          ex.printStackTrace();
       }
       
      
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
      cardNumberTxt.setText("");
      amountTxt.setText("");
      paymentOptionCmb.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextField cardNumberTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> paymentOptionCmb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables


    private void editOptionCombo(PaymentOpt p) {
        try {
           DefaultComboBoxModel optionCombo = (DefaultComboBoxModel) paymentOptionCmb.getModel();
           List<PaymentOpt> paymentOptlist = paymentOptDao.getPaymentOptList();
           for(PaymentOpt paymentOpt: paymentOptlist){
               optionCombo.addElement(paymentOpt);
           }
           optionCombo.setSelectedItem(p);
       } catch (Exception ex) {
          ex.printStackTrace();
       }
    }
}
