/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.hotel.ms.gui;

import az.hotel.ms.dao.ClientDao;
import az.hotel.ms.dao.ReserveDao;
import az.hotel.ms.dao.RoomDao;
import az.hotel.ms.model.Client;
import az.hotel.ms.model.Reservation;
import az.hotel.ms.model.Room;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class EditReserveFrame extends javax.swing.JFrame {
 private  ReserveDao reserveDao;
 private  ClientDao clientDao;
 private  RoomDao roomDao;
 private  Long selectedId;
 private  MainFrame aThis;
    public EditReserveFrame() {
        initComponents();
    }

    EditReserveFrame(ReserveDao reserveDao, ClientDao clientDao, RoomDao roomDao, Long selectedId, MainFrame aThis) {
        try {
          initComponents();
          this.reserveDao = reserveDao;
          this.clientDao = clientDao;
          this.roomDao = roomDao;
          this.selectedId = selectedId;
          this.aThis = aThis;
          Reservation reservation = reserveDao.getReserveById(selectedId);
          editClientCombo(reservation.getClient());
          editRoomCombo(reservation.getRoom());
          reserveDateCmb.setDate(reservation.getReserveDate());
         
      } catch (Exception ex) {
          ex.printStackTrace();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reserveDateCmb = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        clearCmb = new javax.swing.JButton();
        clientCmb = new javax.swing.JComboBox<>();
        roomCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Client Fullname");

        jLabel2.setText("Room Number");

        jLabel3.setText("Reservation Date");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearCmb.setText("Clear");
        clearCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCmbActionPerformed(evt);
            }
        });

        clientCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Client" }));

        roomCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Number" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(reserveDateCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(roomCmb, 0, 149, Short.MAX_VALUE)
                                        .addComponent(clientCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(clientCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(98, 98, 98)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(roomCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(93, 93, 93)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(reserveDateCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(71, 71, 71)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void editRoomCombo(Room r) {
        
        try {
            DefaultComboBoxModel roomCombo = (DefaultComboBoxModel) roomCmb.getModel();
            
            List<Room> roomList = roomDao.getRoomList();
            for(Room room: roomList){
                
                roomCombo.addElement(room);
            }
            roomCombo.setSelectedItem(r);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void editClientCombo(Client c) {
       
        try {
            DefaultComboBoxModel clientCombo = (DefaultComboBoxModel) clientCmb.getModel();
            
            List<Client> clientList = clientDao.getClientList();
            for(Client client: clientList){
                
                clientCombo.addElement(client);
            }
            clientCombo.setSelectedItem(c);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try{
            Client client = (Client) clientCmb.getSelectedItem();
            Room room = (Room) roomCmb.getSelectedItem();
            Date reservDate =  reserveDateCmb.getDate();
            Reservation reservation = reserveDao.getReserveById(selectedId);
            reservation.setClient(client);
            reservation.setRoom(room);
            reservation.setReserveDate(reservDate);
            reserveDao.updateReserve(reservation);
            JOptionPane.showMessageDialog(null,"Reservation has been successfully created!");
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Problem! Reservation has not been successfully created!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
     try {
         aThis.showReserveData(reserveDao.getReservList());
     } catch (Exception ex) {
        ex.printStackTrace();
     }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCmbActionPerformed
        clientCmb.setSelectedIndex(0);
        roomCmb.setSelectedIndex(0);
        reserveDateCmb.setDateFormatString("");
    }//GEN-LAST:event_clearCmbActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearCmb;
    private javax.swing.JComboBox<String> clientCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JDateChooser reserveDateCmb;
    private javax.swing.JComboBox<String> roomCmb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
