/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.hotel.ms.gui;

import az.hotel.ms.dao.ClientDao;
import az.hotel.ms.dao.MenuDao;
import az.hotel.ms.dao.OrdersDao;
import az.hotel.ms.dao.RoomDao;
import az.hotel.ms.model.Client;
import az.hotel.ms.model.Menu;
import az.hotel.ms.model.Orders;
import az.hotel.ms.model.Room;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class NewOrdersFrame extends javax.swing.JFrame {

    private OrdersDao ordersDao;
    private MenuDao menuDao;
    private RoomDao roomDao;
    private MainFrame aThis;
    public NewOrdersFrame() {
        initComponents();
    }
    NewOrdersFrame(OrdersDao ordersDao, MenuDao menuDao, RoomDao roomDao, MainFrame aThis) {
            initComponents();
        this.ordersDao = ordersDao;
        this.menuDao =  menuDao;
        this.roomDao = roomDao;
        this.aThis = aThis;
        showRoomCombo();
        showMenuCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuCmb = new javax.swing.JComboBox<>();
        roomCmb = new javax.swing.JComboBox<>();
        orderCostCmb = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("New Order");

        jLabel1.setText("Menu Name and Description");

        jLabel4.setText("Room Number");

        jLabel5.setText("Cost");

        menuCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Menu" }));

        roomCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room" }));

        orderCostCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCostCmbActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(menuCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderCostCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(roomCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(menuCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roomCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(orderCostCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderCostCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCostCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderCostCmbActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
           menuCmb.setSelectedIndex(0);
           roomCmb.setSelectedIndex(0);
           orderCostCmb.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
         try{
      Menu menu = (Menu) menuCmb.getSelectedItem();   
      Room room = (Room) roomCmb.getSelectedItem();
      double ordersCost = Double.parseDouble(orderCostCmb.getText());
      Orders orders = new Orders();
      orders.setMenu(menu);
      orders.setRoom(room);
      orders.setCost(ordersCost);
      ordersDao.addOrders(orders);
      JOptionPane.showMessageDialog(null,"Orders has been successfully created!");
      
      } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Problem! Orders has not been successfully created!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
         this.dispose();
        try {
            aThis.showOrdersData(ordersDao.getOrdersList());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> menuCmb;
    private javax.swing.JTextField orderCostCmb;
    private javax.swing.JComboBox<String> roomCmb;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

    private void showMenuCombo() {
       
         try {
            DefaultComboBoxModel menuCombo = (DefaultComboBoxModel) menuCmb.getModel();
            
            //DefaultComboBoxModel menuuCombo = (DefaultComboBoxModel) menuDescCmb.getModel();
            List<Menu> menuList = menuDao.getMenuList();
            for(Menu menu: menuList){
                
                menuCombo.addElement(menu);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

 

    private void showRoomCombo() {
         try {
            DefaultComboBoxModel roomCombo = (DefaultComboBoxModel) roomCmb.getModel();
            
            List<Room> roomList = roomDao.getRoomList();
            for(Room room: roomList){
                
                roomCombo.addElement(room);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
