/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.hotel.ms.gui;

import az.hotel.ms.dao.BookingDao;
import az.hotel.ms.dao.ClientDao;
import az.hotel.ms.dao.PaymentDao;
import az.hotel.ms.dao.PaymentOptDao;
import az.hotel.ms.dao.RoomDao;
import az.hotel.ms.model.Booking;
import az.hotel.ms.model.Payment;
import az.hotel.ms.model.PaymentOpt;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class NewPaymentFrame extends javax.swing.JFrame {

    private PaymentDao paymentDao;
    private PaymentOptDao paymentOptDao;
    private BookingDao bookingDao;
    private ClientDao clientDao;
    private RoomDao roomDao;
    private MainFrame aThis;
    public NewPaymentFrame() {
        initComponents();
    }

   
    NewPaymentFrame(PaymentDao paymentDao, PaymentOptDao paymentOptDao, BookingDao bookingDao, ClientDao clientDao, RoomDao roomDao, MainFrame aThis) {
        initComponents();
        this.paymentDao = paymentDao;
        this.paymentOptDao = paymentOptDao;
        this.bookingDao = bookingDao;
        this.clientDao = clientDao;
        this.roomDao = roomDao;
        this.aThis = aThis;
        showBookingCombo();
        showPaymentOptCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cardTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        optionCmb = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Client Fullname and Room");

        clientCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Client and Room" }));

        jLabel3.setText("Card Number");

        jLabel4.setText("Total Amount");

        jLabel5.setText("Payment Option");

        optionCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Option" }));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(optionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(optionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            Booking booking =  (Booking) clientCmb.getSelectedItem();
            Long cardNumber = Long.parseLong(cardTxt.getText());
            Double totalAmount = Double.parseDouble(amountTxt.getText());
            PaymentOpt paymentOpt = (PaymentOpt) optionCmb.getSelectedItem();
            Payment payment = new Payment();
            payment.setBooking(booking);
            payment.setCardNumber(cardNumber);
            payment.setTotalAmount(totalAmount);
            payment.setPaymentOpt(paymentOpt);
            paymentDao.addPayment(payment);
            JOptionPane.showMessageDialog(null,"Payment has been successfully created!");
             
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Problem! Payment has not been successfully created!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
       this.dispose();
        try {
            aThis.showPaymentData(paymentDao.getPaymentList());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextField cardTxt;
    private javax.swing.JComboBox<String> clientCmb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> optionCmb;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

    private void showBookingCombo() {
       
        try {
            DefaultComboBoxModel bookingCombo = (DefaultComboBoxModel) clientCmb.getModel();
            
            //DefaultComboBoxModel menuuCombo = (DefaultComboBoxModel) menuDescCmb.getModel();
            List<Booking> bookingList = bookingDao.getBookingList();
            for(Booking booking: bookingList){
                
                bookingCombo.addElement(booking);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showPaymentOptCombo() {
       
         try {
            DefaultComboBoxModel optionCombo = (DefaultComboBoxModel) optionCmb.getModel();
            
            List<PaymentOpt> paymentOptList = paymentOptDao.getPaymentOptList();
            for(PaymentOpt paymentOpt: paymentOptList){
                
                optionCombo.addElement(paymentOpt);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
